<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Contract_messages{

	public function getOrderContract($day, $month, $year, $name, $company, $address){
		$t = "THIS EQUIPMENT SALE AND SERVICE PROVIDER AGREEMENT is made this ".$day." day of ".$month.", ".$year.", by 
and between Oigo Telematics, LLC a Tennessee corporation with offices at 11600 NW 91th Street, Suite 1, Miami, Florida, 33178 
(the “Company”), and ".$name.", a ".$company." corporation with offices at ".$address." (the “Partner”). 
<BR>
W I T N E S S E T H:
<BR>
  WHEREAS, OIGO TELEMATICS is a provider of M2M Devices and M2M Services; 
<BR>
  WHEREAS, OIGO TELEMATICS’s M2M services are accessible to the Partner via OIGO TELEMATICS’s designated internet site on the World Wide Web; and
<BR>
  WHEREAS, Partner provides M2M services or service to a fleet of vehicles and desires to purchase Oigo Telematic’s M2M Devices and install the equipment (as defined herein) and subscribe to Oigo Telematic’s M2M Services (as defined herein) pursuant to the terms and conditions of this Agreement.
<BR>
NOW THEREFORE, in consideration of the mutual promises and covenants contained herein and for other good and valuable consideration, the receipt and sufficiency of which are hereby acknowledged, the parties intending to be legally bound, hereby agree as follows:
<BR>
This document is bound by and subject to the Terms and Conditions set forth on OIGO TELEMATICS Schedule A (M2M Hardware Device Pricing), Schedule B (M2M Service Plans and Definitions), Schedule C (M2M Service Definitions and others) and Schedule D (M2M Details, Support and Reporting Procedures)  (collectively, this “Agreement”).
 <BR>
 <BR>
 <b><u>OIGO TELEMATICS, LLC EQUIPMENT SALE AND SERVICE PROVIDER AGREEMENT 
<BR>
Terms and Conditions</u></b>
<BR>
OIGO TELEMATICS and Partner agree to the following terms and conditions:
1.  OIGO TELEMATICS EQUIPMENT. The Partner hereby agrees to purchase OIGO TELEMATICS’s: M2M services, M2M devices or equipment, accessories, and all instructional documentation supplied by the manufacturer of the equipment.  (Collectively, the “Equipment”).  The purchase price shall be nonrefundable, except as provided herein. 
<BR>
2.  DEFINITIONS
<BR>
2.1.  The following definitions apply:
“Oigo M2M Services” means the machine-to-machine (“M2M”) communications services that are provide thru a gateway or router which will process data and is provided pursuant to a MSA that allow the transmission of data over Oigo Facilities between M2M Devices and between M2M devices and computer services or other machines in a predetermined process, where such M2M Devices are activated through the Oigo Telematics Software.  
<BR>
 “APN” means access point name, a non-mobile host terminal that supports or provides access to data and applications. Generally, the APN will be configured on the Oigo Facilities and the host network connecting to the Oigo M2M Service. An APN: (i) allows for the dynamic assignment of IP addresses to M2M Devices during active sessions; and (ii) adds routing table entries to allow these specific ranges of IP addresses to access host IP addresses connected to the Oigo M2M Services directly thru the network. 
 <BR>
“Bundled Partner Services” means the unique value-added service provided by Partner to End Partners or End Users (subject to the limitations set forth in this Agreement) under Partner’s label, brand, and marks, which uses or is otherwise combined with the Oigo M2M Services. 
<BR>
“Business Day” or “Day” means any day on which banks are open for the transaction of banking business in the United States of America.
<BR>
“Confidential Information” means all non-public and proprietary information, in any form, disclosed or made available by the disclosing Party to the other Party which: concerns the operations, plans, know-how, trade secrets, business affairs, personnel, products, services, Partners or suppliers of the disclosing Party; or the receiving Party knows or might reasonably expect is regarded by the disclosing Party as the confidential information of the disclosing Party; or is designated as confidential, restricted, proprietary, or with similar designation; or concerns any of the terms or conditions or other facts with respect to this MSA.
<BR>
“CPI” means consumer price index for the United States. 
<BR>
“Distributor” shall mean any individual or legal entity that purchases the Bundled Partner Services from for the purpose of sub-reselling without incorporating such Bundled Services into its own value-added M2M solution.
<BR>
“End Partner” means any Partner of Partner that is not an End User and that combines the Bundled Partner Services with its own unique value-added service for sale to an End User.  
<BR>
“End User” means any final user of the Bundled Partner Service. 
<BR>
“Governmental Authority” means any regulatory agency, court or tribunal having jurisdiction over Oigo Telematics, the Oigo Facilities, the Oigo M2M Services, Partner, the Bundled Partner Services, or the M2M Devices. 
<BR>  
“Identifiers” means the codes and identifiers (including phone numbers, IMEIs, IMSIs, Internet Protocol (IP) addresses, personal identification numbers and e-mail addresses) assigned hereunder to Partner, End Users or M2M Devices in connection with the Oigo Telematics Services. 
<BR>
“Intellectual Property Rights” means all intellectual property rights, including by way of explanation, but not by limitation, those statutory or common law rights in and relating to copyrights, patents, trademarks, trade secrets, moral rights, or any similar rights. 
<BR>
“In-service Date” means the date on which Oigo Telematics will confirm that all the following conditions will have been met: (i) the Oigo M2M Systems and the provisioning of the device are set up, tested and operationally available; (ii) Partner has been trained in connection with the use of the Oigo M2M System.
<BR>
 “M2M Device” means an Oigo-provided wireless device that has been approved and certified by Oigo Telematics for use by End Users in accessing the Oigo M2M Services through the Bundled Partner Services. 
 <BR>
“Roaming Partner” means a third party providing certain Third Party Infrastructures and/or Services, namely, roaming services outside the Oigo Partner Primary Subscribed Network through Roaming Agreements between such Roaming Partner and the Oigo Partner Network Affiliate. Availability of coverage and Services while roaming is not guaranteed.
<BR>
“SIM” means a Subscriber Identity Module provided by Oigo Telematics and required in order for an M2M device to be activated and recognized on the Oigo Facilities and/or the Third Party Facilities and/or Services. 
<BR>
“SIM Status” means the state into which a SIM is automatically placed using the Oigo Systems auto-provisioning feature.
<BR>
“Oigo Subscribed Network” means the wireless data network operated by the Oigo Partner Network Affiliate and used in provision of the Oigo M2M Services.
<BR>
“Oigo M2M Services” means the machine-to-machine (“M2M”) communications services provided pursuant to a MSA that allow the transmission of data over Oigo Facilities between M2M Devices and between M2M devices and computer services or other machines in a predetermined process, where such M2M Devices are activated through the Oigo M2M Systems, as more fully described in this MSA.  
<BR>
“Third Party Facilities and/or Services” means facilities and/or services made available to Oigo Telematics or any of its Affiliates, and/or Partner from a third party vendor, including without limitation any Roaming Partner, appointed by Oigo Telematics or any of its Affiliates to enable Oigo Telematics to provide the Oigo M2M Services to Partner hereunder and include the Oigo M2M Systems.
<BR>
2.2 Other Definitions.  Other terms used in this MSA are defined in the context in which they are used and have the meanings there stated. All terms not otherwise defined herein shall have the meaning ascribed to those terms in the Program Agreement. 
<BR>
3.  REGISTRATION OF EQUIPMENT WITH OIGO TELEMATICS.  All units with service are shipped ready to use OIGO TELEMATICS M2M service; Partner must use the paid service within 18 months of shipment. All services may be renewed at anytime as the terms of contract are meet.
<BR>
4.  APPOINTMENT OF PARTNER AS RESELLER
<BR>
4.1.  Scope of Appointment.  Partner shall only use and resell the Oigo M2M Services in connection with the Bundled Partner Services to End Customers or End Users specified in Section 4.2 below, subject to the conditions and limitations set forth in the Agreement in accordance with Partner’s designated Partner Category. Oigo’s provision of Oigo Telematics M2M Devices and Services under this MSA will not be construed as vesting in Partner any control whatsoever in any facilities and operations of Oigo Telematics or any of its Affiliates or third party vendors, including, but not limited to, the Oigo Facilities, or the Third Party Facilities and/or Services. Partner will not represent itself to any Governmental Authority as an agent, reseller or licensee for or of Oigo Telematics, any Oigo Telematics Affiliate, the Oigo Facilities, or Third Party Facilities and/or Services.  Partner will not enter, directly or indirectly, into any agreement or other arrangement with a third party that gives the third party any rights to purchase the Oigo M2M Service for resale to other parties, except as expressly permitted in Section 4.3 below. Partner may not market or sell the Oigo M2M Services as a standalone service but instead must market and sell the Oigo M2M Services as part of the Bundled Partner Services. Further, Partner may not bill End Customers or End Users separately for the Oigo M2M Services, or otherwise show the Oigo M2M Services as a separate item on its price quotes, pricing schedules or its invoices to the End Customer or End User, but instead must incorporate the cost of the Oigo M2M Services as part of the Bundled Partner Services. Partner will solely determine the price of the Bundled Partner Service it offers to End Customer or End Users.
<BR>
4.2.  Bundled Partner Services. For the avoidance of doubt, the Oigo M2M Services are to be used by Partner solely to enable the provision by Partner of the Bundled Partner Services
<BR>
4.3.  Limitations on Sub-reselling. Partner shall not be authorized to sell the Bundled Partner Services to any individual or legal entity for the purpose of sub-reselling without prior written approval of Oigo, and shall therefore solely be authorized to resell the Oigo M2M Services as part of the Bundled Partner Services to End Customers or End Users subject to the conditions and limitations set forth in the Service Agreement in accordance with Partner’s designated Partner Category, and not to Distributors. 
<BR>
4.4.  Non-exclusivity of Appointment. Oigo Telematics reserves the right to appoint other persons as resellers or agents of the Oigo M2M Services in any area at any time.  Nothing herein shall be construed so as to restrict the activities of Oigo Telematics, acting alone or in concert with others, in connection with the development, implementation, operation, or provision of any products, services or facilities whatsoever, whether similar to or competitive Bundled Partner Services. 
<BR>
5.  PARTNER OBLIGATIONS
<BR>
5.1.  Compliance with Partner Program Terms. Partner agrees to comply with all of Partner’s obligations under the Program Agreement, including without limitation. 
<BR>
5.2.  Bundled Partner Services. Partner is responsible and liable for all services necessary to provide the Bundled Partner Services, such as End Customer and End User credit verification, billing, collection, customer service and support, and all risks and expenses in connection with, related to, or arising out of the provision of the Bundled Partner Services. Partner will not direct any End Customers or End Users to Oigo Telematics for any customer care issues. Partner will report any trouble with respect to the Oigo M2M Services to Oigo Telematics only upon reasonable verification that the trouble is due directly to issues with the Oigo M2M Services and not to elements or conditions within the control of Partner. Partner shall be responsible for complying with all applicable laws and regulations for use of the Oigo M2M Services as part of the Bundled Partner Services including without limitation making or obtaining any required notification or authorizations in the jurisdictions where the Bundled Partner Services are delivered. Partner will not make any representation, warranty, or covenant to any End Customer or End User that would misrepresent or conflict with this Agreement.  
<BR>
5.3.  Unauthorized Use, Fraud and Interference.  The Oigo M2M Services are furnished by Oigo Telematics for use by Partner subject to the condition that there will be no unauthorized, abusive or fraudulent use of the Oigo M2M Services, the Oigo Facilities, Third Party Facilities and/or Services, or the SIMs (collectively the “Unauthorized Use”). Unauthorized Use includes, but is not limited to: (i) attempting or assisting another to access, alter or interfere with the communications of and/or information about another user of the Oigo Facilities or Oigo M2M Services; (ii) tampering with or making an unauthorized connection to the Oigo Facilities; (iii) using or assisting another to use any scheme, false representation or false credit device, or other fraudulent means or devices in connection with the Oigo M2M Services; (iv) attempting or permitting End Users to attempt to use the Oigo M2M Services and/or the Oigo Facilities in such a manner so as to avoid incurring charges for usage; (v) using the Oigo M2M Services in such a manner so as to impair the quality of the Oigo M2M Services or interfere with Oigo Telematics ability to provide the Oigo M2M Services or the use of the Oigo M2M Services by other End Users or customers of Oigo Telematics; or (vi) using the Oigo M2M Services to convey information that is obscene, salacious, abusive, prurient or unlawful. Partner will promptly notify Oigo Telematics of any suspected fraudulent use of the Oigo M2M Services through any M2M Device or if an M2M Device is lost or stolen.  Upon such notification, Oigo Telematics will promptly disable such device(s).  Partner at its expense shall put in place security procedures to minimize the risk of End Customer and End User or third party fraud, including, without limitation, subscription fraud, fraud associated with the use of the Bundled Partner Services, usage on lost or stolen M2M Devices, cloning or network fraud, and fraud committed by Partner’s agents, employees, or representatives.  Oigo Telematics may suspend or terminate the Oigo M2M Services immediately, without prior notice and without any liability to Partner, its End Customer or End Users in case Oigo Telematics reasonably suspects fraud or interference is occurring, although Supplier will, if practical, attempt to contact Partner before such suspension.  Partner agrees to cooperate with Oigo Telematics in the investigation and resolution of all suspect fraud with respect to the OigoM2M Services. 
<BR>
5.4.  Subpoena Compliance. If Partner receives a subpoena requesting production of documents related to the Oigo M2M Services, Partner if not legally prohibited, will promptly notify Oigo Telematics of, and comply with, the subpoena. 
<BR>
5.5.  Privacy and Compliance with Laws. Partner (a) is fully responsible for any unauthorized collection, access, disclosure, and use of all information relating to End Customer’s and End Users’ use of M2M Devices and M2M Services; (b) will implement administrative, physical, and technical safeguards to protect this information; (c) will maintain an up-to-date privacy policy that fully explains (i) what information it collects about its End Customer’s and End Users, (ii) how it uses that information, (iii) how it secures that information, and (iv) to whom it discloses that information; and (d) will comply with all applicable laws, including without limitation data security, privacy, data protection, marketing, and consumer protection laws, including without limitation, any obligation regarding consent and opt-in / opt-out mechanisms. Without limiting the generality of the foregoing, Partner shall clearly disclose to End Customers and End Users that Partner makes no guarantees or warranties that the Bundled Partner Services which include specific solutions, including, by way of example and not limitation, medical/health alert solutions, burglar/security alarm solutions or people tracking solutions, will detect, avert or prevent occurrences of the type for which they are designed.
<BR> 
5.6.  Use of Connections, APN and Oigo Facilities. Partner shall comply with Oigo Telematics Acceptable Use Policy in connection with the use of the connections, the APNs and the Oigo Facilities.  
<BR>
5.7.  Operations Manual. Partner shall at all times comply with the Operations Manual. Partner hereby recognizes and acknowledges that Oigo Telematics may, from time to time, develop and adopt new rules, policies and procedures in addition to those contained in the Operations Manual or elsewhere in this MSA, in connection with the OigoM2M Services, the Oigo Facilities, the Third Party Facilities and/or Services, the APN(s), and/or the Oigo Software including fraud management procedures, security procedures, purchasing procedures, etc. Oigo Telematics shall communicate in writing any additional procedure to Partner and Partner shall comply with same procedures from the date specified therein.
<BR>
5.8.  Relationship with End Customers and End Users. Partner shall be solely responsible for ensuring that the use of the Oigo M2M Devices and Services by End Customer and End Users complies with this MSA. Furthermore, Partner will be solely responsible for: (i) receiving all payments from End Customers and End Users; (ii) all billing, collection of payments and bad debt recovery from End Customers and End Users; and (iii) all customer service and support with respect to End Customers and End Users. Partner agrees that each End Customer and End User will enter into a contract with Partner containing language similar in all material aspects to that contained in this Agreement. Furthermore, Partner shall include language in its End Customer and End User contracts that is the same or substantially and materially consistent with:
<BR>
“[End User/End Customer] expressly understands and agrees that it has no contractual relationship whatsoever with the underlying carrier providing the wireless data services to [Partner] and that [End Customer/End User] is not a third party beneficiary of any agreement between [Partner] and the underlying carrier. In addition, [End Customer/End User] expressly understands and agrees that the underlying carrier makes no representations or warranties whatsoever and shall have no legal, equitable, or other liability of any kind to [End Customer/End User], regardless of the form of the action, whether for breach of contract, warranty, negligence, strict liability in tort or otherwise.”
<BR>
6.  SHORT SHIPMENT AND DEFECTIVE PRODUCT.
<BR>
6.1.  In the event of a shortage or deficiency in a shipment of product, Partner shall give written notice to Oigo Telematics of such claim within 10 calendar days of the subject delivery, failing which the applicable invoice shall be considered payable in accordance with the terms hereof. In the event a product is defective, and Partner gives written notice to Oigo Telematics of such defect in accordance with the foregoing, Partner will provide to Oigo Telematics all information necessary for Oigo Telematics to determine the cause of the defect (including without limitation the identification number(s) of the defective SIM(s)). If Oigo Telematics reasonably determines that the defect is due to issues with the product(s) covered under the warranties obtained from the applicable product manufacturers and not to elements or conditions within the reasonable control of Partner or Partner’s End Customers or End Users, then (i) Partner will upon Oigo Telematics’ request return the defective product(s) to Oigo Telematics solely in accordance with Oigo Telematics’ then-current return procedure, (ii) Oigo Telematics will cancel such defective product(s) and ship new products to Partner in replacement thereof, at Oigo Telematics’ cost. Oigo Telematics shall pay for returned SIMs that are not found to be defective together with the freight, testing and handling costs associated therewith.
<BR>
6.2.  Permitted Use. The products purchased from Oigo Telematics by Partner are only to be installed and used in Oigo Telematic M2M Devices with the Bundled Partner Services and for no other purposes whatsoever. Partner shall not sell, provide, bundle or otherwise distribute any such SIMs other than in the manner set forth herein.
<BR>
7.  INSTALLATION OF EQUIPMENT. The Equipment shall be delivered to the Partner at the point of purchase or dropped-shipped to the Partner.  Partner accepts full and exclusive responsibility for proper installation of the Equipment. OIGO TELEMATICS hereby reserves the right to block any Partner from accessing the Equipment, or to deactivate the Equipment at any time, specifically in cases of non-payment of any obligations due hereunder. UNDER NO CIRCUMSTANCES SHALL OIGO TELEMATICS BE LIABLE TO PARTNER OR ANY OTHER PERSON OR ENTITY (COLLECTIVELY, “PERSON”) FOR ANY LOSS, INJURY OR DAMAGE, OF WHATEVER KIND OR NATURE, RESULTING FROM OR ARISING OUT OF ANY MISTAKES, ERRORS, AND OMISSIONS, ARISING OUT OF OR IN CONNECTION WITH THE INSTALLATION OF THE EQUIPMENT.
<BR>
8.  EQUIPMENT LIMITED WARRANTY. OIGO TELEMATICS warrants that the Equipment shall be free from defects in materials and workmanship and will substantially conform to OIGO TELEMATICS’s applicable published specifications for the Equipment for a period of one (1) year from the date of shipment (the “Equipment Warranty Period”). THIS WARRANTY IS VOID IF THE PRODUCT CASING IS OPENED BY ANYONE OTHER THAN A OIGO TELEMATICS AUTHORIZED SERVICE FACILITY. The warranty set forth in this paragraph shall not apply to the OIGO TELEMATICS M2M Services (as defined herein). Modifications or adjustments to the Equipment, which are not expressly pre-approved in writing by OIGO TELEMATICS, may void Partner’s right or authority to operate the Equipment and any warranty coverage provided hereunder. OIGO TELEMATICS will repair any of its equipment under warranty at no charge to the Partner.
<BR> 
9.  OIGO TELEMATICS M2M SERVICE. 
<BR>
(a) During the term of this Agreement, OIGO TELEMATICS will provide Partner access to and use of the OIGO TELEMATICS M2M Services and the software related thereto (collectively, the “OIGO TELEMATICS SOFTWARE” or “Software”), and OIGO TELEMATICS shall provide Support Services (as defined herein) and other related services that are provided for herein (such OIGO TELEMATICS Software, access, use and services referred to, collectively, as the “M2M Service” or the “OIGO TELEMATICS M2M Service”).
<BR>
(b) The OIGO TELEMATICS M2M Service consists of a hosted web enabled application, data access and storage, carrier interface(s), and email interface. Partner is responsible for obtaining and maintaining all computer equipment, Equipment, software and communications equipment needed or necessary to access the OIGO TELEMATICS M2M Service, and for paying all access charges (e.g., ISP, telecommunications) incurred while using the OIGO TELEMATICS M2M Service. 
<BR>
(c) Upon execution of this Agreement, OIGO TELEMATICS will provide Partner with access to the agreed OIGO TELEMATICS M2M Service for the term of the Agreement.
<BR>
10. SOFTWARE LICENSE. Subject to the provisions of this Agreement, OIGO TELEMATICS hereby grants to Partner a personal, non exclusive, non sub licensable, non-transferable, revocable license (the “License”) to use the OIGO TELEMATICS M2M Service and Software only in accordance with the applicable end user documentation related thereto (“Documentation”) during the term of this Agreement. The License allows for Partner and any Person authorized by Partner (collectively, “Users”) to access remotely and use (only through remote access) the object code version of the OIGO TELEMATICS M2M Service by means of the OIGO TELEMATICS Site. Modifications or adjustments to the Software, which are not expressly pre-approved in writing by OIGO TELEMATICS, may void Partner’s right or authority to operate the license. Partner will not, nor permit any Person to (a) reverse assemble, reverse engineer, decompile or otherwise attempt to derive source code or underlying ideas or algorithms from the OIGO TELEMATICS Software or any component thereof, including the Equipment; or (b) copy, reproduce, modify, translate or create derivative works of, the OIGO TELEMATICS M2M Service, OIGO TELEMATICS Software or any component thereof including the Equipment other than as expressly agreed to in this Agreement.
<BR>
11. OIGO TELEMATICS M2M SERVICE LIMITED WARRANTY. The OIGO TELEMATICS M2M Service included in the Equipment is licensed and not sold. Its use is governed by the provisions of the applicable End User License Agreement (“EULA”), if any, included with the Equipment. In the absence of a separate EULA included with the OIGO TELEMATICS M2M service providing different limited warranty terms, exclusions, and limitations, the following terms and conditions shall apply. OIGO TELEMATICS warrants that the OIGO TELEMATICS M2M service will substantially conform to the applicable published specifications for the OIGO TELEMATICS M2M service for a period of ninety (90) days from the date of valid activation (the “Software Warranty Period”). OIGO TELEMATICS does not warrant that the operation of the OIGO TELEMATICS M2M service M2M service will be error-free or uninterrupted or that the OIGO TELEMATICS Software functions will meet Partner’s requirements or that all defects in the OIGO TELEMATICS M2M service will be corrected. THIS WARRANTY IS VOID IF PARTNER BREACHES THE SOFTWARE LICENSE SET FORTH IN SECTION 6 OF THIS AGREEMENT.
<BR>
12. OIGOCARE INSURANCE PROGRAM. OIGO TELEMATICS M2M Service includes eligibility for all Oigo Devices activated and serviced under all of Oigo Telematics M2M Service or Software Plans to the Oigocare Insurance Program. Partner Devices enrolled in the Oigo Insurance Program may at any time after the initial warranty period and during the term of this agreement, execute a warranty claim for a device so long as the claim is for a device that has been in service for a minimum uninterrupted period of twelve (12) consecutive months prior to the date of the claim. Payment by Partner to Oigo Telematics of an insurance deductible fee of US$15 is required to enter an Oigocare Insurance Claim. Furthermore, the Partner must be in good financial standing with Oigo Telematics with a payment history that does not include any past due invoices nor unpaid invoices for the device included in the claim. Oigo Telematics may at it sole discretion offer the Partner Warranty Repair or Replacement under the same terms of the initial Manufacturers Warranty. Oigo Telematics may also offer the Partner the possibility of a trade in program for any of its other devices (including future 3G and 4G product) so long as the Partner Device has been in service for a minimum uninterrupted period of twelve (12) consecutive months, the Partner is in good financial standing with Oigo Telematics and the Partner returns the old device along with a payment of an Insurance Deductible Fee of US$15 at the time of the claim. 
<BR>
13. WARRANTY REMEDIES. OIGO TELEMATICS’s sole liability and Partner’s exclusive remedy under the Equipment and Software Limited Warranties set forth above shall be, at OIGO TELEMATICS’s option, to repair or replace any Equipment or Software that fails to conform to such warranty (“Nonconforming Product”), or refund the purchase price paid by Partner for any such Nonconforming Product, upon Partner’s return of any Nonconforming Product to OIGO TELEMATICS in accordance with OIGO TELEMATICS’s standard return procedures. OIGO TELEMATICS will not pay for (a) costs of installation or removal, (b) costs of product set-up or adjustment, or (c) shipping or related charges of returning the Nonconforming Product for repair, regardless of whether the repair is covered by the Limited Warranties set forth above. Partner must pay for shipment of the Nonconforming Product to the nearest OIGO TELEMATICS Authorized Service Facility and, if the warranty claim is valid, OIGO TELEMATICS will pay for shipment of the repaired or replaced Nonconforming Product back to Partner. All replaced parts and products, and products on which a refund is made, become the property of OIGO TELEMATICS. Unless prohibited by law, new or reconditioned parts may be used in the performance of warranty service. Repaired or replaced parts are warranted for the remainder of the original applicable limited warranty period. Partner will be charged for the repair or replacement of the Nonconforming Product made after the expiration of the applicable warranty period.
<BR>
14. EQUIPMENT AND SOFTWARE LIMITED WARRANTIES. The Equipment and Software Limited Warranties are conditioned upon submission of a purchase receipt or other proof of the date of original purchase and the preceding warranties shall not apply to, and OIGO TELEMATICS shall not be responsible for: (a) damage, failure or malfunction caused by or attributable to acts of God, lightning or other incidence of excess voltage or current, fresh or salt water immersion or spray, abuse, neglect, accident, misuse, alteration, cosmetic damage or any other occurrence beyond the reasonable control of OIGO TELEMATICS; (b) the Equipment and Software, if they are not properly and correctly installed, configured, interfaced, maintained, stored, and operated in accordance with the relevant operator's manual and specifications; (c) Services not provided by OIGO TELEMATICS; (d) the combination or utilization of the Equipment or Software with accessories, products, information, data, systems, devices or ancillary or peripheral equipment not made, supplied or specified by OIGO TELEMATICS; (e) the operation of the Equipment or Software under any specification other than, or in addition to, the standard specifications for the Equipment or Software; (f) the Equipment and Software if the serial number has been removed or defaced; (g) any repairs other than those provided by a OIGO TELEMATICS Authorized Service Facility; (h) consumable parts (e.g., batteries and fuses); (i) the unauthorized modification or use of the Equipment or Software; or (k) any shipment of the Equipment (claims must be presented to the carrier).
<BR>
15. MEMBER ACCOUNT, PASSWORD, ACCESS CODE AND SECURITY. Partner shall access the OIGO TELEMATICS Service by means of the internet connection and/or internet browser that is recommended by OIGO TELEMATICS and using equipment obtained by Partner as further described in this Agreement.  Partner may then choose its own password and account name.  In all cases Partner shall assign, record and control the use of the User Access Codes and will be solely responsible for any use thereof. OIGO TELEMATICS will not be responsible for the use or misuse of any User Access Code. Partner is entirely responsible for: (a) maintaining confidentiality with regard to its password and account information, and (b) any and all activities that occur under Partner’s account. OIGO TELEMATICS will not be held liable for any unauthorized access to Partner’s account by any Person other than Partner and/or any third party claims and/or actions associated therewith.
<BR>
16. SUPPORT SERVICES. OIGO TELEMATICS shall provide online support services (“Support Services”) to Partners through its Help Desk support program during such times as indicated on the OIGO TELEMATICS Site. The Help Desk support program allows Partner to access Support Services by calling its telephone number or by sending an email to support@oigotelematics.com.  OIGO TELEMATICS shall not be required to provide Support Services: (a) to any Person other than Partner, and (b) in respect of any software other than the OIGO TELEMATICS Software.
<BR>
17. FEES. In addition to the payment of the purchase price for the Equipment, Partner shall pay to OIGO TELEMATICS the renewal fees when Partner’s subscription expires if Partner wishes to continue the service. 
<BR>
17.1. Subscription Plans and equipment are provided with pre-activated status / test ready mode and will turn into fully active mode as soon as they are registered with an authorized device. All purchased equipment must turn into fully active mode within 180 days from the day of shipment. Failure to fully activate the equipment will cause the equipment to be permanently inactive after 180 days. Upon completion of the initial term of initial 12-month term all MRC and YRC subscription plans will continue to be automatically renewed and billed under the same subscription plan unless otherwise notified by the Subscriber. It will be the Subscriber’s sole responsibility to notify Provider of their wish to modify or cancel the subscription plan prior to the completion of the initial term and subsequent terms thereafter. After the initial 12-month term all MRC plans will be billed on a Month-to-Month Basis and can be canceled at any time without any penalties or cancelation charges. YRC Plans may be cancelled at any time and are subject to forfeit of any remaining months should subscription plan be cancelled prior to expiration date. 
<BR>
17.2. EQUIPMENT THAT IS PERMANENTLY INACTIVE STATUS MAY BECOME USELESS AND MAY NOT BE USED INDEPENDANTLY WITH ANOTHER SERVICE PROVIDER OR SIMCARD. UNITS SHIPPED UNDER MRC OR YRC PLANS ARE EXCLUSIVE TO THE PROVIDER AND ARE PROTECTED AGAINST FRAUDULANT USE. ATTEMPTED USE WITH ANOTHER SERVICE PROVIDER OR SIMCARD IS STRICTLY PROHIBBITED, CONSIDERED FRAUDULANT AND VIOLATES THE TERMS OF THIS AGREEMENT.  
<BR>
17.3. No more than 20% of total active equipment can roam in territories of USA and Canada at any given time.
<BR>
18. TAXES. Prices set out herein are exclusive of all taxes and Partner shall pay (and OIGO TELEMATICS shall have no liability for), any taxes, tariffs, duties and other charges or assessments imposed or levied by any government or governmental agency in connection with this Agreement, except for taxes based solely on the net income of OIGO TELEMATICS (collectively, “Taxes”). Partner will pay when due or upon OIGO TELEMATICS’s demand all Taxes, fines and penalties relating to this Agreement or the Equipment that are now or in the future assessed or levied by any state, local or other government authority. Partner shall indemnify and hold harmless OIGO TELEMATICS from and against any and all liability or damages, including late charges and interest that OIGO TELEMATICS may incur by reason of the assessment of Taxes.
<BR>
19. OWNERSHIP OF INTELLECTUAL PROPERTY. Partner acknowledges and agrees that OIGO TELEMATICS shall retain and own all right, title and interest and all intellectual property rights (including copyrights, trade secrets, trademarks and patent rights) in and to the Equipment, OIGO TELEMATICS Software, Documentation and the OIGO TELEMATICS Site (collectively, the “OIGO TELEMATICS Materials”) and all copies thereof, and that nothing herein transfers or conveys to Partner any ownership right, title or interest in or to the OIGO TELEMATICS Materials or to any copy thereof or any license right with respect to same not expressly granted herein. Partner agrees that it will not, either during or after the termination of this Agreement, contest or challenge OIGO TELEMATICS’s ownership in the OIGO TELEMATICS Materials or any of its intellectual property rights therein.
<BR>
20. PARTNER SECURITY RESPONSIBILITIES. Partner shall notify OIGO TELEMATICS immediately if there is a security breach or unauthorized use of the Service. If OIGO TELEMATICS determines, in its sole discretion, that any unauthorized use of the Service has occurred, OIGO TELEMATICS shall have the right to immediately suspend or terminate Partner’s use of the Service.
<BR>
21. LIMITED WARRANTY REGARDING SERVICE. OIGO TELEMATICS warrants that the Service will substantially conform to the related Documentation. Partner's sole and exclusive remedies and OIGO TELEMATICS's entire obligations to Partner, any User or any other Person hereunder for any breach of this warranty or the failure of OIGO TELEMATICS to provide the Service as required herein (a “Deficiency”), shall be, at OIGO TELEMATICS’s election, for OIGO TELEMATICS to (a) provide the Services that are the subject of the Deficiency, or (b) refund to Partner the fees paid to OIGO TELEMATICS in the calendar year in respect of the Deficiency first arose. The remedies in this Section 17 are Partner’s sole and exclusive remedy for any breach or alleged breach of any warranty to Partner and are expressly in lieu of any or all other remedies which may be available to Partner resulting from the furnishing, the failure to furnish or the quality of any Service. OIGO TELEMATICS does not warrant the accuracy of any data or information furnished to Partner that is created from Partner data, Partner systems or software supplied by Partner.
<BR>
22. WARRANTY DISCLAIMER REGARDING EQUIPMENT, SOFTWARE, SERVICES AND PROPRIETARY INFORMATION. 
<BR>
(a) THE WARRANTIES ABOVE STATE OIGO TELEMATICS’S ENTIRE LIABILITY, AND PARTNER’S EXCLUSIVE REMEDIES, RELATING TO PERFORMANCE OF THE EQUIPMENT, SOFTWARE AND SERVICES. EXCEPT AS OTHERWISE EXPRESSLY PROVIDED HEREIN, THE EQUIPMENT, SOFTWARE, SERVICES, THE PROPRIETARY INFORMATION, AND ACCOMPANYING ACCESSORIES AND MATERIALS ARE PROVIDED “AS-IS” AND WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND BY OIGO TELEMATICS, ITS AUTHORIZED DISTRIBUTORS OR ANY PERSON WHO HAS BEEN INVOLVED IN ITS CREATION, PRODUCTION, INSTALLATION, OR DISTRIBUTION INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NONINFRINGEMENT. THE STATED EXPRESS WARRANTIES ARE IN LIEU OF ALL OBLIGATIONS OR LIABILITIES ON THE PART OF OIGO TELEMATICS ARISING OUT OF, OR IN CONNECTION WITH, ANY EQUIPMENT, SOFTWARE, SERVICES OR PROPRIETARY INFORMATION. OIGO TELEMATICS IS NOT RESPONSIBLE FOR THE OPERATION OR FAILURE OF OPERATION OF GPS SATELLITES OR THE AVAILABILITY OF GPS SATELLITE SIGNALS. UNDER NO CIRCUMSTANCES SHALL OIGO TELEMATICS BE LIABLE FOR ANY LOSS, INJURY OR DAMAGE, OF WHATEVER KIND OR NATURE, RESULTING FROM OR ARISING OUT OF ANY MISTAKES, ERRORS, OMISSIONS, DELAYS OR INTERRUPTIONS IN THE RECEIPT, TRANSMISSION OR STORAGE OF ANY MESSAGES, SIGNALS OR INFORMATION ARISING OUT OF OR IN CONNECTION WITH THE SERVICES OR USE OF ANY UNDERLYING CARRIER'S WIRELESS NETWORK.  IF ANY IMPLIED WARRANTY APPLIES TO THE EQUIPMENT, SOFTWARE, SERVICES OR THE PROPRIETARY INFORMATION, SUCH IMPLIED WARRANTY IS LIMITED IN DURATION TO THE DURATION OF THE EXPRESS LIMITED WARRANTIES SET FORTH ABOVE. SOME STATES AND JURISDICTIONS DO NOT ALLOW LIMITATIONS ON DURATION OR THE EXCLUSION OF AN IMPLIED WARRANTY, SO THE ABOVE LIMITATION MAY NOT APPLY TO PARTNER. PARTNER MAY ALSO HAVE ADDITIONAL RIGHTS NOT STATED IN THIS DOCUMENT. IF ANY PORTION OF THE LIMITED WARRANTIES PROVIDED HEREIN IS ILLEGAL OR UNENFORCEABLE, SUCH PARTIAL ILLEGALITY OR UNENFORCEABILITY SHALL NOT AFFECT THE REMAINDER OF THE LIMITED WARRANTIES.
<BR>
(b) OIGO TELEMATICS DOES NOT REPRESENT OR WARRANT THAT: (i) THE SERVICES WILL MEET PARTNER'S REQUIREMENTS; (ii) THE SERVICES WILL BE ERROR-FREE OR UNINTERRUPTED OR THAT THE RESULTS OBTAINED FROM THEIR USE WILL BE CORRECT, ACCURATE OR RELIABLE; OR (iii) ALL DEFICIENCIES IN THE SERVICES CAN BE FOUND OR CORRECTED. FURTHER, THE SERVICES MAY BE INTERRUPTED OR UNAVAILABLE FOR THE PURPOSES OF PERFORMING MAINTENANCE OR UPGRADES. OIGO TELEMATICS WILL NOT BE RESPONSIBLE FOR: (1) SERVICE IMPAIRMENTS CAUSED BY ACTS WITHIN THE CONTROL OF PARTNER OR ANY USER; (2) INTEROPERABILITY OF SPECIFIC PARTNER APPLICATIONS OR EQUIPMENT; (3) INABILITY OF PARTNER TO ACCESS OR INTERACT WITH ANY OTHER SERVICE PROVIDERS THROUGH THE INTERNET, OTHER NETWORKS OR USERS THAT COMPRISE THE INTERNET OR THE INFORMATIONAL OR COMPUTING RESOURCES AVAILABLE THROUGH THE INTERNET; (4) SERVICES PROVIDED BY SERVICE PROVIDERS OTHER THAN OIGO TELEMATICS; OR (5) PERFORMANCE IMPAIRMENTS CAUSED ON THE INTERNET.
<BR>
(c) The agents, employees, distributors and dealers of OIGO TELEMATICS are not authorized to make modifications to the express Limited Warranties set forth herein, or make additional warranties, whether express or implied, binding on OIGO TELEMATICS. Accordingly, additional statements such as dealer advertising or presentation, whether oral or written, do not constitute warranties by OIGO TELEMATICS and should not be relied upon.
<BR>
23. LIMITATION OF LIABILITY.  
<BR>
(a) FOR ANY BREACH OR DEFAULT BY OIGO TELEMATICS OF ANY OF THE PROVISIONS OF THIS AGREEMENT, OR WITH RESPECT TO ANY CLAIM ARISING FROM PARTNER’S USE OF THE EQUIPMENT, SOFTWARE, SERVICES OR OTHERWISE ARISING UNDER THIS AGREEMENT OR RELATED HERETO, OIGO TELEMATICS’S ENTIRE LIABILITY SHALL IN NO EVENT EXCEED THE LESSER OF THE FOLLOWING: (i) THE FEES PAID TO OIGO TELEMATICS BY PARTNER PURSUANT TO THIS AGREEMENT IN THE SIX (6) MONTH PERIOD IMMEDIATELY PRECEDING THE DATE ON WHICH THE CAUSE OF ACTION FIRST AROSE, EVEN IF THE CAUSE OF ACTION IS A CONTINUING ONE, OR (ii) IN THE AGGREGATE WITH RESPECT TO ALL CLAIMS MADE UNDER OR RELATED TO THIS AGREEMENT, THE AMOUNT PAID BY PARTNER DURING THE FIRST CALENDAR YEAR UNDER THIS AGREEMENT. 
<BR>
(b) IN NO EVENT WILL OIGO TELEMATICS BE LIABLE FOR ANY DIRECT, SPECIAL, INCIDENTAL, INDIRECT, PUNITIVE, EXEMPLARY OR CONSEQUENTIAL LOSSES OR DAMAGES, INCLUDING, WITHOUT LIMITATION LOST BUSINESS REVENUE, LOSS OF PROFITS, LOSS OF DATA, LOSS OF COVER, DAMAGES FOR DELAY, FAILURE TO REALIZE EXPECTED PROFITS OR SAVINGS OR ANY CLAIM AGAINST PARTNER BY ANY OTHER PERSON, EVEN IF OIGO TELEMATICS HAS BEEN ADVISED OF THE POSSIBILITY OF ANY SUCH LOSSES OR DAMAGES.
<BR>
(c) OIGO TELEMATICS SHALL NOT BE LIABLE FOR UNAUTHORIZED ACCESS TO OR ALTERATION, THEFT, LOSS OR DESTRUCTION OF ANY DATA, EQUIPMENT OR THE SERVICES, INCLUDING THROUGH ACCIDENT, FRAUDULENT MEANS OR DEVICES, OR ANY OTHER METHOD.
<BR>
(d) OIGO TELEMATICS SHALL BE LIABLE TO PARTNER ONLY AS EXPRESSLY PROVIDED IN THIS AGREEMENT BUT SHALL HAVE NO OTHER OBLIGATION, DUTY, OR LIABILITY WHATSOEVER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE TO PARTNER. THE LIMITATIONS, EXCLUSIONS AND DISCLAIMERS IN THIS AGREEMENT SHALL APPLY IRRESPECTIVE OF THE NATURE OF THE CAUSE OF ACTION, DEMAND, OR ACTION BY PARTNER, INCLUDING BREACH OF CONTRACT, NEGLIGENCE, TORT, OR ANY OTHER LEGAL THEORY AND SHALL SURVIVE A FUNDAMENTAL BREACH OR BREACHES OR THE FAILURE OF THE ESSENTIAL PURPOSE OF THIS AGREEMENT OR OF ANY REMEDY CONTAINED HEREIN. SOME STATES AND JURISDICTIONS DO NOT ALLOW LIMITATIONS ON DURATION OR THE EXCLUSION OF AN IMPLIED WARRANTY, SO THE ABOVE LIMITATION MAY NOT APPLY TO PARTNER.
<BR>
(e) Neither party may bring an action, regardless of form, arising out of or related to this Agreement (other than to recover fees or expenses due to either party) more than one year after the cause of action has arisen.
<BR>
(f) Partner agrees to indemnify and hold OIGO TELEMATICS and its Affiliates (as defined herein), and its and their employees, officers, directors, shareholders and agents harmless from and against any claims, suits, actions or proceedings (collectively, “Claims”) brought and damages, costs (including reasonable attorneys’ fees and costs) arising from, related to, or in connection with: (i) Claims by any Person to the extent that such Claims are based upon or arise out of Partner’s use of the Equipment or Services; (ii) breach by Partner of this Agreement; or (iii) Partner’s failure to comply with all applicable laws, rules or regulations; or (iv) any other action or omission by Partner. 
<BR>
24. TERM OF AGREEMENT. This Agreement and the License granted herein shall continue during the applicable Service period. (the “Term”).
<BR>
25. Termination.
<BR>
(a) You may cancel or terminate services associated with subscription plan at any time by sending a written request email to info@oigotelematics.com.  The Services for those identified subscription plans will be canceled or terminated immediately without any prejudice, starting an irreversible process. You are liable for all charges incurred under your account prior to any cancellation or termination and we have the right to charge and collect all pending invoices related to the subscription service plan prior to the cancellation or termination of service. Service due for Subscription Plans canceled prior to completion of the initial 12-month term will immediately become due for payment and will be billed and collected in conjunction with service plan termination. Services which are or were prepaid or that have not been delivered will be forfeited with no reimbursement or money due to the customer regardless of if they are in active state or pending activation. If Partner fails to pay any amount chargeable hereunder when due, then OIGO TELEMATICS may, in addition to any other rights or remedies at law or under this Agreement, and in its sole discretion, (i) suspend or deny Partner’s access to or use of the Service or the performance of any of its obligations under this Agreement until such failure is remedied, subject to such conditions as OIGO TELEMATICS may require; and/or (ii) terminate this Agreement;
<BR>
(b) If Partner fails to pay any amount chargeable hereunder when due, then OIGO TELEMATICS may, in addition to any other rights or remedies at law or under this Agreement, and in its sole discretion, (i) suspend or deny Partner’s access to or use of the Service or the performance of any of its obligations under this Agreement until such failure is remedied, subject to such conditions as OIGO TELEMATICS may require; and/or (ii) terminate this Agreement
<BR>
(c) This Agreement may be immediately terminated or Service suspended by OIGO TELEMATICS (i) if a receiver, trustee, administrator, or administrative receiver is appointed for the Partner or its property; (ii) if Partner makes an assignment for the benefit of creditors; (iii) if any proceedings should be commenced by or against the Partner under any bankruptcy, insolvency, or debtor’s relief law, and such proceedings shall not be vacated or set aside within thirty (30) days from the date of commencement thereof; or (iv) the Partner is liquidated or dissolved; or
<BR>
(d) This Agreement may be terminated by either party in the event the other party materially breaches any of its duties, obligations or responsibilities under this Agreement (other than breaches discussed in Section 24(a) or (b) hereof), and fails to cure such breach or provide the other party with an acceptable plan for curing such breach within thirty (30) days after receipt by the breaching party of written notice specifying the breach.
<BR>
(e) Suspension. Without prejudice to Oigo’s Telematic right to terminate this MSA pursuant to this Section, Oigo may also suspend the Oigo M2M Services for as long as a breach by Partner remains uncured, provided written notice is provided by Oigo Telematics to Partner, as applicable under this MSA, and in the event that Oigo Telematic’s ability to provide the Oigo M2M Services is prevented or substantially prevented or restricted by any Force Majeure Event
<BR>
26. EFFECT OF TERMINATION. Except to the extent agreed to in writing by the parties, upon the termination of this Agreement:
<BR>
(a) OIGO TELEMATICS shall be entitled to immediately cease providing the Services.
<BR>
(b) OIGO TELEMATICS shall be entitled to immediately terminate Partner’s access to the OIGO TELEMATICS M2M Service.
<BR>
(c) Either Partner or OIGO TELEMATICS shall immediately pay to the other all amounts owing under this Agreement as of the date of termination.
<BR>
(d) If this Agreement is terminated by OIGO TELEMATICS under Section 24(a), 24(b) or 24(c), all amounts that would have become due under this Agreement shall automatically accelerate and become immediately due and payable by Partner to OIGO TELEMATICS. If terminated by Partner under Section 24(c), OIGO TELEMATICS shall immediately pay Partner any amounts due.
<BR>
(e) Except as specifically provided in Section 25(d) above, OIGO TELEMATICS shall have no obligation to refund any amounts to Partner.
<BR>
(f) Partner shall, and shall cause its Users to, immediately and permanently cease to use, in any manner whatsoever, the OIGO TELEMATICS M2M Service, the User Access Codes and the Documentation.
<BR>
(G) The License granted under Section 6 will automatically terminate.
<BR>
27. NOTIFICATIONS.  Legal notices will be provided to the respective senior executives, with copies to the respective legal department as per the table below.  Either Party may change the persons to whom notices will be sent by giving notice to the other.
<BR>
28. SURVIVAL. The provisions of this Agreement that by their nature are intended to survive the expiration or earlier termination, including, without limitation, those provisions relating to termination, ownership, confidential information, warranty disclaimer, indemnification and limitations of liability shall survive the expiration or earlier termination of this Agreement.
<BR>
29. WIRELESS SERVICE.  Partner acknowledges and agrees that the Equipment, Software and Service use, and require, industry standard cellular wireless communications services to communicate with vehicles, and therefore, all such vehicles must be within cellular coverage to communicate.  Partner further acknowledges and agrees that OIGO TELEMATICS is not the underlying wireless carrier and that OIGO TELEMATICS may contract with various wireless carriers from time to time to provide such wireless service.  UNDER NO CIRCUMSTANCES SHALL OIGO TELEMATICS BE LIABLE TO PARTNER OR ANY OTHER PERSON OR ENTITY FOR ANY LOSS, INJURY OR DAMAGE, OF WHATEVER KIND OR NATURE, RESULTING FROM OR ARISING OUT OF ANY MISTAKES, ERRORS, OMISSIONS, DELAYS OR INTERRUPTIONS IN THE RECEIPT, TRANSMISSION OR STORAGE OF ANY MESSAGES, SIGNALS OR INFORMATION ARISING OUT OF OR IN CONNECTION WITH THE SERVICES OR USE OF ANY UNDERLYING CARRIER'S WIRELESS NETWORK.  PARTNER UNDERSTANDS THAT OIGO TELEMATICS CANNOT GUARANTY THE SECURITY OF WIRELESS TRANSMISSIONS, AND WILL NOT BE LIABLE FOR ANY LACK OF SECURITY RELATING TO THE USE OF THE SERVICES. THE SERVICE IS FOR PARTNER’S USE ONLY AND PARTNER MAY NOT RESELL THE SERVICE TO ANY OTHER PARTY. 
<BR>
Services provided by Provider are intended for Asset Tracking, M2M, IOT and Telemetry Applications. USING THE SERVICES FOR ANY UNLAWFUL ACTIVITY, OR ANY ACTIVITY THAT ADVERSELY AFFECTS THE INTEREST OF ANY ONE IS PROHIBITED.
<BR>
You may validate available countries, coverage and participating international authorized distributors by contacting provider or by viewing the following internet address: http://www.oigotelematics.com.
<BR>
30. MISCELLANEOUS.
<BR>
(a) Notice. (b) Force Majeure. Except for payment obligations hereunder, if the performance of this Agreement, or any obligation thereunder is prevented, restricted, or interfered with by reason of: fire, flood, earthquake, explosion or other casualty or accident or act of God; strikes or labor disputes; inability to procure or obtain delivery of parts, supplies, power, telecommunication services, equipment or software from suppliers; war or other violence; any law, order proclamation, regulation, ordinance, demand or requirement of any governmental authority; or any other act or condition whatsoever beyond the reasonable control of the affected party, the party so affected shall be excused from such performance to the extent of such prevention, restriction or interference; provided, however, that the party so affected shall take reasonable steps to avoid or remove such cause of non-performance and shall promptly resume performance hereunder whenever such causes are removed.
<BR>
(b) Partner Rights. Nothing in this Agreement shall create or vest in Partner any right, title, or interest in the OIGO TELEMATICS Application Service or the OIGO TELEMATICS Materials other than the limited right to use the Service under the terms and conditions of this Agreement. All such rights shall remain solely in OIGO TELEMATICS.
<BR>
(c) Severability. To the extent that any provision, portion or extent of this Agreement is deemed to be invalid, illegal or unenforceable, such provision, portion or extent shall be severed and deleted or limited so as to give effect to the intent of the parties insofar as possible and the remainder of this Agreement, as the case may be, shall remain binding upon the parties.
<BR>
(d) Assignment. Partner may not, without OIGO TELEMATICS's prior written consent, assign or transfer this Agreement or any of its rights or obligations under this Agreement to any Person.  OIGO TELEMATICS may assign this Agreement to any Person without the consent of Partner. OIGO TELEMATICS may delegate to Affiliates of OIGO TELEMATICS and to agents, suppliers and contractors of OIGO TELEMATICS any of the obligations herein imposed upon OIGO TELEMATICS and OIGO TELEMATICS may disclose to any such Persons any information required by them to perform the duties so delegated to them. For purposes of this Agreement, the defined term, “Affiliate” with respect to any Person shall mean any Person which, directly or indirectly, through one or more intermediaries, controls the subject Person or any Person which is controlled by or is under common control with a controlling Person.  For purposes of this definition, “control” (including the correlative terms “controlling”, “controlled by” and “under common control with”), with respect to any Person, means possession, directly or indirectly, of the power to direct or cause the direction of the management and policies of such Person, whether through the ownership of voting securities or by contract or otherwise.
<BR>
(e) Waiver and Amendment. OIGO TELEMATICS reserves the right to change the terms and conditions of this Agreement or its policies relating to the Service at any time.  Continued use of the Service for more than thirty (30) days after any such change shall constitute Partner’s consent to such changes. No waiver by any party of any right or remedy under this Agreement shall be effective unless such waiver is in writing and signed by the party to be charged with such waiver.  No waiver by any party shall be deemed to extend to any prior or subsequent or breach of this Agreement or affect in any way any rights arising by virtue of any prior or subsequent occurrence.
<BR>
(f) Governing Law; Venue. This Agreement shall be governed by and construed in accordance with the laws of the State of Tennessee without reference to conflict or choice of law rules or principles. The parties irrevocably and unconditionally submit to the exclusive jurisdiction of the court of the State of Tennessee located in Knox County or in the United States District Court for the District of Tennessee for the purposes of any suit, action or other proceeding arising out of this Agreement or the subject matter hereof brought by any party hereto; and hereby waive and agree not to assert as a defense or otherwise, in any such suit action or proceeding, any claim that it is not subject personally to the jurisdiction of the above-named courts, that its property is exempt or immune from attachment or execution, that the suit, action or proceeding is brought in an inconvenient forum, that the venue of the suit, action or proceeding is improper or that this Agreement or the subject matter hereof may not be enforced by such court. Partner hereby agrees that it is reasonable and foreseeable that it may appear in a state or federal Knox County court in connection with any dispute between the parties under this Agreement.
<BR>
(g) Attorneys’ Fees.  If any legal action is necessary in order to enforce any of the terms of this Agreement or otherwise as a result of the relationship between Partner and OIGO TELEMATICS, the prevailing party in any such action shall be entitled to recover its reasonable attorneys' fees and costs from the non-prevailing party.
<BR>
(h) Entire Agreement.  This Agreement (together with any Schedules attached hereto and incorporated herein) sets forth the entire understanding and supersedes prior agreements between the parties relating to the subject matter contained herein and merges all prior discussions between them, and neither party shall be bound by any definition, condition, provision, representation, warranty, covenant or promise other than as expressly stated in this Agreement or as it contemporaneously or subsequently set forth in writing and executed by a duly authorized officer or representative of the party to be bound thereby.
<BR>";
 return $t;
	}
}
?>